### ISSUE TITLE
QueryStringBuilder does not URL encode the query string

### ISSUE THREAD

**Issue by vanillajonathan** [civicsource/webapi-utils#6]
Note that the `QueryStringBuilder` does not URL encode the query string.

The `AddQueryString` method of the `Query​Helpers` class which resides in the `Microsoft.AspNetCore.WebUtilities` namespace does this.

https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.webutilities.queryhelpers

**Comment by chadly** [comment]
Thanks for the link. Wasn't aware of that implementation.
